export const PricingData = [
  // 0: Web Development
  [
    {
      title: "Startup MVP",
      name: "Web Development",
      price: "2,499",
      billing: "fixed milestone",
      timeline: "2 - 3 weeks",
      description: "Fast-track prototype or MVP designed to validate your product and acquire initial users.",
      features: [
        "Next.js 14 & React responsive frontend",
        "Essential REST API backend integration",
        "Authentication & database setup (PostgreSQL / Supabase)",
        "Mobile-first responsive design",
        "30-day post-launch warranty support",
      ],
      popular: false,
    },
    {
      title: "Growth Platform",
      name: "Web Development",
      price: "4,999",
      billing: "fixed milestone",
      timeline: "4 - 6 weeks",
      description: "Comprehensive full-stack web application with advanced workflows, permissions, and dashboards.",
      features: [
        "Full-stack Next.js with Server Actions",
        "Role-based access control (RBAC)",
        "Stripe / Payment gateway integration",
        "Automated CI/CD deployment pipeline",
        "Real-time analytics and audit logs",
        "60-day hyper-care support",
      ],
      popular: true,
    },
    {
      title: "Enterprise Custom",
      name: "Web Development",
      price: "8,999",
      billing: "fixed milestone",
      timeline: "8 - 12 weeks",
      description: "High-throughput microservices architecture with custom integrations, compliance, and dedicated SLA.",
      features: [
        "Custom distributed microservices architecture",
        "High-availability multi-region cloud setup",
        "Rigorous automated security & penetration audit",
        "Dedicated senior engineering pod",
        "Enterprise SLA with 24/7 incident response",
      ],
      popular: false,
    },
  ],

  // 1: UI/UX & Design Systems
  [
    {
      title: "Design Audit & Wireframes",
      name: "UI/UX Design",
      price: "1,499",
      billing: "fixed milestone",
      timeline: "1 - 2 weeks",
      description: "Heuristic evaluation and wireframing sprint to optimize product user experience and retention.",
      features: [
        "Comprehensive heuristic usability audit",
        "Low & mid-fidelity user journey wireframes",
        "Information architecture restructuring",
        "Executive design strategy report",
      ],
      popular: false,
    },
    {
      title: "Full Product Design System",
      name: "UI/UX Design",
      price: "3,499",
      billing: "fixed milestone",
      timeline: "3 - 5 weeks",
      description: "End-to-end interactive Figma design system with components, design tokens, and user testing.",
      features: [
        "Pixel-perfect Figma component library",
        "Interactive prototypes for user testing",
        "Dark & light mode design tokens",
        "Developer handoff documentation & Storybook sync",
      ],
      popular: true,
    },
    {
      title: "Complete Brand & App Suite",
      name: "UI/UX Design",
      price: "5,999",
      billing: "fixed milestone",
      timeline: "6 - 8 weeks",
      description: "Holistic brand identity, custom illustrations, marketing landing pages, and multi-device app design.",
      features: [
        "Complete corporate brand identity & logo suite",
        "Web & native mobile interface designs",
        "Custom 2D/3D vector illustration assets",
        "Design systems governance training for your team",
      ],
      popular: false,
    },
  ],

  // 2: Cloud Architecture & DevOps
  [
    {
      title: "Cloud Infrastructure Setup",
      name: "Cloud & DevOps",
      price: "1,899",
      billing: "fixed milestone",
      timeline: "1 - 2 weeks",
      description: "Foundational cloud environment provisioning on AWS, GCP, or Vercel with modern security guardrails.",
      features: [
        "VPC network, firewall, and IAM roles setup",
        "Docker containerization of existing apps",
        "Managed database setup with automated backups",
        "SSL/TLS and DNS certificate automation",
      ],
      popular: false,
    },
    {
      title: "Automated CI/CD & Scaling",
      name: "Cloud & DevOps",
      price: "3,999",
      billing: "fixed milestone",
      timeline: "3 - 4 weeks",
      description: "High-availability automated release pipelines with automated regression testing and staging setups.",
      features: [
        "GitHub Actions zero-downtime blue/green deployments",
        "Kubernetes (EKS / GKE) cluster orchestration",
        "Telemetry, APM (Datadog/Grafana), and alerting",
        "Infrastructure as Code (Terraform) scripts",
      ],
      popular: true,
    },
    {
      title: "Multi-Cloud & Compliance",
      name: "Cloud & DevOps",
      price: "7,499",
      billing: "fixed milestone",
      timeline: "6 - 8 weeks",
      description: "Enterprise compliance hardening (SOC2, HIPAA, ISO) with multi-region disaster recovery failover.",
      features: [
        "Multi-region active-active failover setup",
        "SOC2 and HIPAA cloud security controls implementation",
        "Automated vulnerability scanning & DDoS protection",
        "24/7 SLA infrastructure monitoring",
      ],
      popular: false,
    },
  ],

  // 3: AI & Intelligent Automation
  [
    {
      title: "AI API Integration",
      name: "AI Solutions",
      price: "2,499",
      billing: "fixed milestone",
      timeline: "2 - 3 weeks",
      description: "Seamless integration of state-of-the-art LLMs (OpenAI, Claude) into your existing application.",
      features: [
        "OpenAI & Anthropic Claude API connections",
        "Structured output parsing & validation",
        "Prompt engineering & guardrail sanitization",
        "Usage telemetry and cost-capping controls",
      ],
      popular: false,
    },
    {
      title: "Enterprise RAG Pipeline",
      name: "AI Solutions",
      price: "4,999",
      billing: "fixed milestone",
      timeline: "4 - 5 weeks",
      description: "Custom semantic search and contextual question-answering over your proprietary documents and knowledge base.",
      features: [
        "Vector database indexing (Pinecone / Qdrant)",
        "Document parsing (PDF, DOCX, CSV, Notion)",
        "Hybrid keyword & semantic retrieval algorithms",
        "Hallucination mitigation & citation linking",
      ],
      popular: true,
    },
    {
      title: "Autonomous Agent System",
      name: "AI Solutions",
      price: "7,999",
      billing: "fixed milestone",
      timeline: "6 - 8 weeks",
      description: "Multi-agent automation platform capable of planning, browsing, querying external APIs, and executing tasks.",
      features: [
        "Multi-agent LangGraph / CrewAI workflow engine",
        "External ERP, CRM & database tool calling",
        "Human-in-the-loop approval workflows",
        "Comprehensive benchmark evaluation test suite",
      ],
      popular: false,
    },
  ],

  // 4: Cross-Platform Mobile Apps
  [
    {
      title: "Mobile MVP",
      name: "Mobile App",
      price: "3,499",
      billing: "fixed milestone",
      timeline: "3 - 5 weeks",
      description: "Cross-platform mobile application for iOS and Android built with React Native and Expo.",
      features: [
        "Single codebase for iOS and Android",
        "Authentication & user profile management",
        "Push notification integration (Firebase FCM)",
        "App Store & Google Play submission assistance",
      ],
      popular: false,
    },
    {
      title: "Production Mobile Suite",
      name: "Mobile App",
      price: "6,499",
      billing: "fixed milestone",
      timeline: "6 - 8 weeks",
      description: "Full-featured native-feel mobile platform with offline caching, camera/GPS access, and in-app purchases.",
      features: [
        "In-app purchases & subscription handling (RevenueCat)",
        "Offline-first SQLite synchronization",
        "Biometric FaceID / Fingerprint authentication",
        "Deep linking & universal attribution setup",
      ],
      popular: true,
    },
    {
      title: "Enterprise Mobile Ecosystem",
      name: "Mobile App",
      price: "9,999",
      billing: "fixed milestone",
      timeline: "10 - 14 weeks",
      description: "High-scale mobile app integrated with enterprise ERP, real-time WebSockets, and customized hardware peripherals.",
      features: [
        "Custom native Swift & Kotlin module bridging",
        "High-performance Bluetooth / IoT device connectivity",
        "End-to-end encrypted messaging & VoIP",
        "Dedicated mobile QA device testing lab",
      ],
      popular: false,
    },
  ],

  // 5: E-Commerce Solutions
  [
    {
      title: "Modern Storefront",
      name: "E-Commerce",
      price: "2,799",
      billing: "fixed milestone",
      timeline: "2 - 4 weeks",
      description: "High-speed storefront with custom catalog, frictionless checkout, and payment processing.",
      features: [
        "Next.js headless e-commerce frontend",
        "Stripe / PayPal multi-currency checkout",
        "Automated inventory management",
        "Mobile optimized responsive cart",
      ],
      popular: false,
    },
    {
      title: "Scale E-Commerce Engine",
      name: "E-Commerce",
      price: "5,299",
      billing: "fixed milestone",
      timeline: "5 - 7 weeks",
      description: "Custom commerce architecture with loyalty rewards, dynamic pricing, and ERP integration.",
      features: [
        "Headless Shopify or Medusa.js backend",
        "Custom promo codes, bundles & tiered discounts",
        "Automated shipping label & tracking webhooks",
        "Sub-second catalog search with Algolia",
      ],
      popular: true,
    },
    {
      title: "Omnichannel Global Commerce",
      name: "E-Commerce",
      price: "8,499",
      billing: "fixed milestone",
      timeline: "8 - 12 weeks",
      description: "Enterprise multi-vendor or multi-currency marketplace with automated vendor split payments and tax compliance.",
      features: [
        "Multi-vendor marketplace split payment engine",
        "Automated global sales tax compliance (Stripe Tax / Avalara)",
        "Warehouse inventory ERP synchronization",
        "Omnichannel POS & Web checkout integration",
      ],
      popular: false,
    },
  ],
];
